import random

def get_quest_events():
    return [
        "You take your position at the village gates, scanning the horizon for any threats.",
        "The torches flicker as the wind howls through the trees. You tighten your grip on your weapon.",
        "A distant howl echoes in the night. You brace yourself, remaining vigilant.",
        "A merchant passes by, nodding at you in gratitude for keeping the village safe.",
        "You hear rustling in the bushes. Your heart pounds as you prepare for anything.",
        "The night drags on, but you stand firm, unwavering in your duty.",
        "A shadow moves in the distance. Could it be an enemy, or just the wind playing tricks on you?",
        "Your shift is nearly over, but fatigue begins to creep in. You shake it off and stay alert.",
        "You hear faint footsteps behind you, turning around only to see a stray cat stretching lazily.",
        "A traveling bard sings off-key in the distance. You wonder if that's the real threat.",
        "The wind picks up, howling through the trees like a ghostly wail.",
        "You hear a dog barking in the distance. Someone's pet, or something more sinister?",
        "A group of bats flutters by overhead, disappearing into the night.",
        "You see a figure in the mist... it’s just a scarecrow someone left outside the gates.",
        "The scent of fresh bread wafts from the village bakery. You envy those sleeping inside.",
        "You see a shooting star and make a wish. You wish for the shift to end sooner.",
        "You hear whispers, but it's just another guard talking to himself to stay awake.",
        "A firefly lands on your hand, glowing softly. You wonder if it's trying to tell you something.",
        "A distant torch goes out. You tighten your grip on your weapon, just in case.",
        "A guard sneezes so loudly that even the trees seem startled.",
        "The night air is crisp. You suddenly crave a hot meal, but duty calls.",
        "A crow lands near you and stares. You stare back. It blinks first. You win.",
        "A sudden gust of wind makes the trees sway. Could something be lurking there?",
        "You spot an owl perched on a tree branch, watching you with curiosity.",
        "A fellow guard starts humming a song. You nod in rhythm but don't join in.",
        "Your armor creaks slightly as you shift your weight. Time is moving slowly.",
        "You hear a loud snap in the woods. Your heart pounds as you grip your weapon... it’s just a deer stepping on a twig.",
        "A group of fireflies lights up the area, creating a brief moment of beauty in the darkness.",
        "The distant howl from earlier gets closer. Turns out it was just the bard trying out falsetto.",
        "A branch falls from a tree, narrowly missing your head. You glare at the tree in suspicion.",
        "You hear faint whispers, but no one is there. Or are they?",
        "A rat scurries by with a stolen piece of bread from a guard's rations.",
        "You see a torch flicker oddly in the distance. Probably just the wind. Probably.",
        "The cold air sends shivers down your spine. You remind yourself to stay strong.",
        "A figure appears at the far end of the road, only to vanish when you blink.",
        "A crow caws loudly above. You silently hope it’s not a bad omen.",
        "You hear a faint clang of metal in the distance. Another guard, or something else?",
        "A distant bell tolls. Midnight. Halfway through your shift.",
        "Your boots feel heavier with each passing minute. The night seems endless.",
        "A dog runs by, seemingly on an important mission of its own.",
        "A small glowing light appears on the road... it's just a lantern beetle.",
        "A rustling sound in the bushes makes you jump, but it's just a rabbit hopping by.",
        "You take a deep breath, focusing on your duty despite the eerie silence.",
        "A strange noise makes you turn around. Nothing there... yet.",
        "You hear distant chanting but can’t make out the words. Probably just the wind... hopefully.",
        "A warm breeze momentarily cuts through the cold, offering a brief moment of comfort.",
        "A fellow guard tries to start small talk. You respond with a simple nod.",
        "The stars twinkle above, indifferent to the night’s events.",
        "A guard lets out a loud yawn. It’s contagious. You stifle your own.",
        "A wooden signpost creaks as the wind pushes against it.",
        "A suspiciously well-dressed rat scurries by. You feel like it’s plotting something.",
        "A bat swoops low over your head, nearly making you drop your weapon.",
        "A sudden noise in the woods sends chills down your spine.",
        "Your fingers twitch from the cold. The night is testing your endurance.",
        "You see your breath in the cold night air. The village remains still.",
        "A single leaf drifts down, catching the moonlight as it falls.",
        "The sun finally rises, signaling the end of your watch. Another night successfully defended."
    ]
